services:
  - type: web
    name: old-covenant-server
    env: node
    plan: free
    rootDir: .
    buildCommand: cd server && npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
